### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [D1rk9ghT/Recon#1]

**Comment by sasholy** [comment]
GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
what is it? thx

**Comment by D1rk9ghT** [comment]
file has been updated please check

**Comment by D1rk9ghT** [comment]
fixed
